[package]
name = "scrooge"
version = "0.1.0"
authors = ["Milo123459"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
structopt = "0.3.21"
chrono = "0.4.20"